// prisma/seedMedidas.ts

import { PrismaClient } from '../src/generated/prisma'
import { PrismaPg } from '@prisma/adapter-pg'
import dotenv from 'dotenv'

dotenv.config()

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! })
const prisma = new PrismaClient({ adapter })

async function main() {
  console.log('Iniciando seed de Medidas de Controle e Causas Provaveis...')

  // Limpa dados anteriores para permitir re-seed
  await prisma.medidaControle.deleteMany()
  await prisma.causaProvavel.deleteMany()
  console.log('Tabelas limpas.')

  // ============================================================
  // MEDIDAS DE CONTROLE
  // ============================================================
  const medidas = [
    // --- CARGA DE TRABALHO ---
    // Critico
    { categoria: 'Carga de Trabalho', fatorNR1: 'Exigencias da tarefa', nivelRisco: 'Critico', tipo: 'ORGANIZACIONAL', titulo: 'Revisao emergencial de quadro de pessoal', descricao: 'Realizar levantamento imediato da relacao demanda x capacidade por setor, com contratacao emergencial ou redistribuicao de tarefas em ate 30 dias.', responsavel: 'RH + Gestao do Setor', prazoSugerido: 'Imediato (30 dias)', referenciaLegal: 'NR-1 item 1.5.3; ISO 45003 seção 6.2', prioridade: 1 },
    { categoria: 'Carga de Trabalho', fatorNR1: 'Exigencias da tarefa', nivelRisco: 'Critico', tipo: 'ORGANIZACIONAL', titulo: 'Suspensao de horas extras sistematicas', descricao: 'Proibir horas extras recorrentes nos setores criticos ate que a causa raiz seja tratada. Implementar controle de jornada rigoroso.', responsavel: 'RH + Diretoria', prazoSugerido: 'Imediato (15 dias)', referenciaLegal: 'CLT art. 59; NR-1 item 1.5.3', prioridade: 1 },
    { categoria: 'Carga de Trabalho', fatorNR1: 'Exigencias da tarefa', nivelRisco: 'Critico', tipo: 'INDIVIDUAL', titulo: 'Programa de recuperacao psicossocial', descricao: 'Disponibilizar atendimento psicologico emergencial para colaboradores dos setores com carga critica. Encaminhar casos graves ao SESMT.', responsavel: 'SESMT + RH', prazoSugerido: 'Imediato (15 dias)', referenciaLegal: 'NR-1; NR-7', prioridade: 1 },
    // Alto
    { categoria: 'Carga de Trabalho', fatorNR1: 'Exigencias da tarefa', nivelRisco: 'Alto', tipo: 'ORGANIZACIONAL', titulo: 'Mapeamento e redistribuicao de tarefas', descricao: 'Realizar mapeamento de processos dos setores sobrecarregados, identificar gargalos e redistribuir atividades com base em criterios de capacidade.', responsavel: 'Gestao do Setor + RH', prazoSugerido: 'Curto prazo (60 dias)', referenciaLegal: 'NR-1 item 1.5.3; ISO 45003 seção 6.2', prioridade: 2 },
    { categoria: 'Carga de Trabalho', fatorNR1: 'Exigencias da tarefa', nivelRisco: 'Alto', tipo: 'ORGANIZACIONAL', titulo: 'Implantacao de pausas programadas', descricao: 'Estabelecer pausas obrigatorias durante a jornada para setores com demanda intensa, conforme recomendacoes ergonomicas.', responsavel: 'SESMT + Gestao', prazoSugerido: 'Curto prazo (30 dias)', referenciaLegal: 'NR-17 item 17.6.3', prioridade: 2 },
    { categoria: 'Carga de Trabalho', fatorNR1: 'Exigencias da tarefa', nivelRisco: 'Alto', tipo: 'COLETIVA', titulo: 'Comite de gestao de carga de trabalho', descricao: 'Criar comite mensal com representantes dos setores para monitorar volume de trabalho, priorizar demandas e propor ajustes.', responsavel: 'RH + Gestores', prazoSugerido: 'Medio prazo (90 dias)', referenciaLegal: 'ISO 45003 seção 8.2', prioridade: 2 },
    // Moderado
    { categoria: 'Carga de Trabalho', fatorNR1: 'Exigencias da tarefa', nivelRisco: 'Moderado', tipo: 'ORGANIZACIONAL', titulo: 'Revisao periodica de metas e prazos', descricao: 'Instituir revisao trimestral de metas por setor, ajustando expectativas ao quadro real disponivel.', responsavel: 'Gestao + Diretoria', prazoSugerido: 'Medio prazo (90 dias)', referenciaLegal: 'ISO 45003 seção 6.2', prioridade: 3 },
    { categoria: 'Carga de Trabalho', fatorNR1: 'Exigencias da tarefa', nivelRisco: 'Moderado', tipo: 'COLETIVA', titulo: 'Treinamento em gestao de tempo e priorizacao', descricao: 'Oferecer capacitacao pratica sobre gestao de tempo, priorizacao de demandas e tecnicas de organizacao pessoal.', responsavel: 'RH', prazoSugerido: 'Medio prazo (90 dias)', referenciaLegal: 'ISO 45003 seção 8.3', prioridade: 3 },
    // Baixo
    { categoria: 'Carga de Trabalho', fatorNR1: 'Exigencias da tarefa', nivelRisco: 'Baixo', tipo: 'ORGANIZACIONAL', titulo: 'Monitoramento continuo de indicadores de carga', descricao: 'Manter acompanhamento trimestral de horas extras, absenteismo e volume de tarefas por setor para identificar deterioracao precoce.', responsavel: 'RH + SESMT', prazoSugerido: 'Continuo', referenciaLegal: 'NR-1 item 1.5.4; ISO 45003 seção 9', prioridade: 4 },

    // --- AUTONOMIA E CONTROLE ---
    { categoria: 'Autonomia e Controle', fatorNR1: 'Grau de autonomia', nivelRisco: 'Critico', tipo: 'ORGANIZACIONAL', titulo: 'Redesenho de processos com delegacao estruturada', descricao: 'Reestruturar fluxos de trabalho para garantir margens minimas de decisao aos colaboradores. Eliminar microgerenciamento sistematico.', responsavel: 'Diretoria + Gestores', prazoSugerido: 'Imediato (30 dias)', referenciaLegal: 'ISO 45003 seção 6.2.2', prioridade: 1 },
    { categoria: 'Autonomia e Controle', fatorNR1: 'Grau de autonomia', nivelRisco: 'Critico', tipo: 'COLETIVA', titulo: 'Implantacao de espacos de escuta e participacao', descricao: 'Criar canais formais (reunioes quinzenais, caixas de sugestao ativas) para que colaboradores participem de decisoes que afetam seu trabalho.', responsavel: 'RH + Gestores', prazoSugerido: 'Imediato (30 dias)', referenciaLegal: 'ISO 45003 seção 6.2.2; NR-1', prioridade: 1 },
    { categoria: 'Autonomia e Controle', fatorNR1: 'Grau de autonomia', nivelRisco: 'Alto', tipo: 'ORGANIZACIONAL', titulo: 'Revisao de alçadas de decisao por funcao', descricao: 'Mapear niveis de decisao por cargo e ampliar a autonomia operacional onde o controle excessivo nao se justifica.', responsavel: 'Gestores + RH', prazoSugerido: 'Curto prazo (60 dias)', referenciaLegal: 'ISO 45003 seção 6.2.2', prioridade: 2 },
    { categoria: 'Autonomia e Controle', fatorNR1: 'Grau de autonomia', nivelRisco: 'Alto', tipo: 'INDIVIDUAL', titulo: 'Capacitacao de liderancas sobre gestao participativa', descricao: 'Treinar gestores em lideranca participativa, delegacao eficaz e comunicacao horizontal.', responsavel: 'RH + Desenvolvimento', prazoSugerido: 'Curto prazo (60 dias)', referenciaLegal: 'ISO 45003 seção 8.3', prioridade: 2 },
    { categoria: 'Autonomia e Controle', fatorNR1: 'Grau de autonomia', nivelRisco: 'Moderado', tipo: 'COLETIVA', titulo: 'Grupos de melhoria continua com participacao ativa', descricao: 'Implementar grupos de melhoria continua (Kaizen, circulos de qualidade) com participacao voluntaria dos colaboradores.', responsavel: 'Gestao + RH', prazoSugerido: 'Medio prazo (90 dias)', referenciaLegal: 'ISO 45003 seção 8.2', prioridade: 3 },
    { categoria: 'Autonomia e Controle', fatorNR1: 'Grau de autonomia', nivelRisco: 'Baixo', tipo: 'ORGANIZACIONAL', titulo: 'Pesquisa periodica de percepcao de autonomia', descricao: 'Incluir indicadores de autonomia percebida nas avaliacoes periodicas para monitorar evolucao.', responsavel: 'RH', prazoSugerido: 'Continuo', referenciaLegal: 'ISO 45003 seção 9', prioridade: 4 },

    // --- RELACOES INTERPESSOAIS ---
    { categoria: 'Relacoes Interpessoais', fatorNR1: 'Relacoes socioprofissionais', nivelRisco: 'Critico', tipo: 'ORGANIZACIONAL', titulo: 'Ativacao de protocolo anti-assedio', descricao: 'Implantar ou reforcar canal de denuncia anonimo, comite de etica e procedimento de apuracao com prazo maximo de 15 dias. Afastar envolvidos se necessario.', responsavel: 'RH + Juridico + Diretoria', prazoSugerido: 'Imediato (15 dias)', referenciaLegal: 'Lei 14.457/2022; NR-1; ISO 45003 seção 6.2.3', prioridade: 1 },
    { categoria: 'Relacoes Interpessoais', fatorNR1: 'Relacoes socioprofissionais', nivelRisco: 'Critico', tipo: 'INDIVIDUAL', titulo: 'Acolhimento psicologico para vitimas', descricao: 'Disponibilizar atendimento psicologico especializado imediato para colaboradores que relataram sofrer assedio ou desrespeito.', responsavel: 'SESMT + RH', prazoSugerido: 'Imediato (7 dias)', referenciaLegal: 'NR-7; ISO 45003', prioridade: 1 },
    { categoria: 'Relacoes Interpessoais', fatorNR1: 'Relacoes socioprofissionais', nivelRisco: 'Alto', tipo: 'COLETIVA', titulo: 'Programa de convivencia e respeito', descricao: 'Realizar workshops sobre comunicacao nao-violenta, respeito a diversidade e resolucao de conflitos em todos os setores.', responsavel: 'RH + Desenvolvimento', prazoSugerido: 'Curto prazo (60 dias)', referenciaLegal: 'ISO 45003 seção 8.3', prioridade: 2 },
    { categoria: 'Relacoes Interpessoais', fatorNR1: 'Relacoes socioprofissionais', nivelRisco: 'Alto', tipo: 'ORGANIZACIONAL', titulo: 'Politica formal de prevencao de assedio', descricao: 'Publicar e divulgar politica institucional de prevencao ao assedio moral e sexual, com sancoes claras e canal de denuncia acessivel.', responsavel: 'RH + Juridico', prazoSugerido: 'Curto prazo (45 dias)', referenciaLegal: 'Lei 14.457/2022; CLT', prioridade: 2 },
    { categoria: 'Relacoes Interpessoais', fatorNR1: 'Relacoes socioprofissionais', nivelRisco: 'Moderado', tipo: 'COLETIVA', titulo: 'Acoes de integracao e fortalecimento de equipe', descricao: 'Promover atividades periodicas de integracao entre equipes para fortalecer vinculos e cooperacao.', responsavel: 'RH + Gestores', prazoSugerido: 'Medio prazo (90 dias)', referenciaLegal: 'ISO 45003 seção 8.2', prioridade: 3 },
    { categoria: 'Relacoes Interpessoais', fatorNR1: 'Relacoes socioprofissionais', nivelRisco: 'Baixo', tipo: 'ORGANIZACIONAL', titulo: 'Monitoramento de clima relacional', descricao: 'Manter indicadores de clima relacional e conflitos nas pesquisas periodicas. Atuar preventivamente em sinais de deterioracao.', responsavel: 'RH', prazoSugerido: 'Continuo', referenciaLegal: 'ISO 45003 seção 9', prioridade: 4 },

    // --- LIDERANCA E GESTAO ---
    { categoria: 'Lideranca e Gestao', fatorNR1: 'Estilo de gestao', nivelRisco: 'Critico', tipo: 'ORGANIZACIONAL', titulo: 'Intervencao imediata na gestao do setor', descricao: 'Avaliar a atuacao do gestor do setor critico. Considerar substituicao, afastamento ou coaching emergencial. Ouvir colaboradores em sigilo.', responsavel: 'Diretoria + RH', prazoSugerido: 'Imediato (15 dias)', referenciaLegal: 'NR-1; ISO 45003 seção 6.2.4', prioridade: 1 },
    { categoria: 'Lideranca e Gestao', fatorNR1: 'Estilo de gestao', nivelRisco: 'Alto', tipo: 'INDIVIDUAL', titulo: 'Programa de desenvolvimento de liderancas', descricao: 'Inscrever gestores em programa estruturado de desenvolvimento de competencias: feedback, escuta ativa, gestao humanizada.', responsavel: 'RH + Desenvolvimento', prazoSugerido: 'Curto prazo (60 dias)', referenciaLegal: 'ISO 45003 seção 8.3', prioridade: 2 },
    { categoria: 'Lideranca e Gestao', fatorNR1: 'Estilo de gestao', nivelRisco: 'Alto', tipo: 'ORGANIZACIONAL', titulo: 'Implantacao de avaliacao 360 de gestores', descricao: 'Implementar processo de avaliacao de gestores por suas equipes (anonima), com devolutiva obrigatoria e plano de acao individual.', responsavel: 'RH', prazoSugerido: 'Curto prazo (90 dias)', referenciaLegal: 'ISO 45003 seção 9', prioridade: 2 },
    { categoria: 'Lideranca e Gestao', fatorNR1: 'Estilo de gestao', nivelRisco: 'Moderado', tipo: 'COLETIVA', titulo: 'Rodas de conversa lideranca-equipe', descricao: 'Instituir encontros mensais entre lideranca e equipe para alinhamento, escuta e construcao conjunta de solucoes.', responsavel: 'Gestores + RH', prazoSugerido: 'Medio prazo (90 dias)', referenciaLegal: 'ISO 45003 seção 8.2', prioridade: 3 },
    { categoria: 'Lideranca e Gestao', fatorNR1: 'Estilo de gestao', nivelRisco: 'Baixo', tipo: 'ORGANIZACIONAL', titulo: 'Mentoria continua para gestores', descricao: 'Manter programa de mentoria e atualizacao continua para liderancas, com foco em saude psicossocial e gestao de pessoas.', responsavel: 'RH', prazoSugerido: 'Continuo', referenciaLegal: 'ISO 45003 seção 8.3', prioridade: 4 },

    // --- RECONHECIMENTO E CRESCIMENTO ---
    { categoria: 'Reconhecimento e Crescimento', fatorNR1: 'Reconhecimento', nivelRisco: 'Critico', tipo: 'ORGANIZACIONAL', titulo: 'Revisao emergencial de politica de reconhecimento', descricao: 'Diagnosticar ausencia de reconhecimento nos setores criticos. Implementar acoes imediatas: feedbacks semanais obrigatorios, reconhecimento publico.', responsavel: 'Diretoria + RH + Gestores', prazoSugerido: 'Imediato (30 dias)', referenciaLegal: 'ISO 45003 seção 6.2.5', prioridade: 1 },
    { categoria: 'Reconhecimento e Crescimento', fatorNR1: 'Reconhecimento', nivelRisco: 'Alto', tipo: 'ORGANIZACIONAL', titulo: 'Programa estruturado de reconhecimento', descricao: 'Criar programa formal de reconhecimento (mensal/trimestral) com criterios claros, envolvendo pares e lideranca.', responsavel: 'RH + Gestores', prazoSugerido: 'Curto prazo (60 dias)', referenciaLegal: 'ISO 45003 seção 6.2.5', prioridade: 2 },
    { categoria: 'Reconhecimento e Crescimento', fatorNR1: 'Reconhecimento', nivelRisco: 'Alto', tipo: 'ORGANIZACIONAL', titulo: 'Plano de carreira e desenvolvimento', descricao: 'Estruturar trilhas de desenvolvimento profissional com criterios transparentes de progressao.', responsavel: 'RH + Diretoria', prazoSugerido: 'Medio prazo (120 dias)', referenciaLegal: 'ISO 45003 seção 6.2.5', prioridade: 2 },
    { categoria: 'Reconhecimento e Crescimento', fatorNR1: 'Reconhecimento', nivelRisco: 'Moderado', tipo: 'COLETIVA', titulo: 'Cultura de feedback positivo', descricao: 'Treinar liderancas e equipes em praticas de feedback construtivo e reconhecimento entre pares.', responsavel: 'RH', prazoSugerido: 'Medio prazo (90 dias)', referenciaLegal: 'ISO 45003 seção 8.3', prioridade: 3 },
    { categoria: 'Reconhecimento e Crescimento', fatorNR1: 'Reconhecimento', nivelRisco: 'Baixo', tipo: 'ORGANIZACIONAL', titulo: 'Monitoramento de percepcao de reconhecimento', descricao: 'Acompanhar indicadores de reconhecimento percebido nas pesquisas periodicas. Manter acoes que funcionam.', responsavel: 'RH', prazoSugerido: 'Continuo', referenciaLegal: 'ISO 45003 seção 9', prioridade: 4 },

    // --- EQUILIBRIO TRABALHO-VIDA ---
    { categoria: 'Equilibrio Trabalho-Vida', fatorNR1: 'Jornada de trabalho', nivelRisco: 'Critico', tipo: 'ORGANIZACIONAL', titulo: 'Politica de desconexao digital', descricao: 'Implementar politica de desconexao: proibir demandas fora do horario de trabalho exceto emergencias reais. Bloquear envio de mensagens corporativas fora da jornada.', responsavel: 'Diretoria + RH', prazoSugerido: 'Imediato (15 dias)', referenciaLegal: 'CLT; ISO 45003 seção 6.2.6', prioridade: 1 },
    { categoria: 'Equilibrio Trabalho-Vida', fatorNR1: 'Jornada de trabalho', nivelRisco: 'Alto', tipo: 'ORGANIZACIONAL', titulo: 'Flexibilizacao de jornada', descricao: 'Avaliar viabilidade de horario flexivel, banco de horas ou trabalho hibrido para setores compativeis.', responsavel: 'RH + Gestores', prazoSugerido: 'Curto prazo (60 dias)', referenciaLegal: 'CLT art. 59; ISO 45003', prioridade: 2 },
    { categoria: 'Equilibrio Trabalho-Vida', fatorNR1: 'Jornada de trabalho', nivelRisco: 'Alto', tipo: 'COLETIVA', titulo: 'Sensibilizacao sobre limites de jornada', descricao: 'Realizar campanhas internas sobre importancia do descanso, direito a desconexao e impactos da sobrecarga na saude.', responsavel: 'RH + Comunicacao', prazoSugerido: 'Curto prazo (45 dias)', referenciaLegal: 'ISO 45003 seção 8.3', prioridade: 2 },
    { categoria: 'Equilibrio Trabalho-Vida', fatorNR1: 'Jornada de trabalho', nivelRisco: 'Moderado', tipo: 'INDIVIDUAL', titulo: 'Programa de qualidade de vida', descricao: 'Oferecer acoes de bem-estar: ginastica laboral, meditacao, grupos de atividade fisica, apoio nutricional.', responsavel: 'RH + SESMT', prazoSugerido: 'Medio prazo (90 dias)', referenciaLegal: 'NR-17; ISO 45003', prioridade: 3 },
    { categoria: 'Equilibrio Trabalho-Vida', fatorNR1: 'Jornada de trabalho', nivelRisco: 'Baixo', tipo: 'ORGANIZACIONAL', titulo: 'Monitoramento de horas extras e absenteismo', descricao: 'Manter dashboard de horas extras e absenteismo por setor para detectar sinais precoces de desequilibrio.', responsavel: 'RH', prazoSugerido: 'Continuo', referenciaLegal: 'NR-1 item 1.5.4', prioridade: 4 },

    // --- CLAREZA DE PAPEL ---
    { categoria: 'Clareza de Papel', fatorNR1: 'Exigencias da tarefa', nivelRisco: 'Critico', tipo: 'ORGANIZACIONAL', titulo: 'Redesenho imediato de descricoes de cargo', descricao: 'Atualizar descricoes de cargo e responsabilidades de todos os setores criticos, com validacao conjunta entre gestor e equipe.', responsavel: 'RH + Gestores', prazoSugerido: 'Imediato (30 dias)', referenciaLegal: 'ISO 45003 seção 6.2.7', prioridade: 1 },
    { categoria: 'Clareza de Papel', fatorNR1: 'Exigencias da tarefa', nivelRisco: 'Alto', tipo: 'ORGANIZACIONAL', titulo: 'Matriz de responsabilidades (RACI)', descricao: 'Elaborar matriz RACI para processos-chave, eliminando sobreposicoes e lacunas de responsabilidade.', responsavel: 'Gestores + RH', prazoSugerido: 'Curto prazo (60 dias)', referenciaLegal: 'ISO 45003 seção 6.2.7', prioridade: 2 },
    { categoria: 'Clareza de Papel', fatorNR1: 'Exigencias da tarefa', nivelRisco: 'Moderado', tipo: 'COLETIVA', titulo: 'Reunioes de alinhamento de expectativas', descricao: 'Instituir reunioes trimestrais de alinhamento entre lideranca e equipe sobre expectativas, entregas e prioridades.', responsavel: 'Gestores', prazoSugerido: 'Medio prazo (60 dias)', referenciaLegal: 'ISO 45003 seção 8.2', prioridade: 3 },
    { categoria: 'Clareza de Papel', fatorNR1: 'Exigencias da tarefa', nivelRisco: 'Baixo', tipo: 'ORGANIZACIONAL', titulo: 'Revisao anual de descricoes de cargo', descricao: 'Manter ciclo anual de revisao de descricoes de funcao com participacao dos ocupantes.', responsavel: 'RH', prazoSugerido: 'Continuo', referenciaLegal: 'ISO 45003 seção 9', prioridade: 4 },

    // --- SEGURANCA E CONDICOES ---
    { categoria: 'Seguranca e Condicoes', fatorNR1: 'Condicoes do ambiente', nivelRisco: 'Critico', tipo: 'ORGANIZACIONAL', titulo: 'Inspecao emergencial de seguranca', descricao: 'Realizar inspecao imediata das condicoes fisicas e psicologicas de seguranca nos setores criticos. Corrigir irregularidades em ate 15 dias.', responsavel: 'SESMT + Manutencao', prazoSugerido: 'Imediato (15 dias)', referenciaLegal: 'NR-1; NR-4; NR-12; ISO 45003 seção 6.2.8', prioridade: 1 },
    { categoria: 'Seguranca e Condicoes', fatorNR1: 'Condicoes do ambiente', nivelRisco: 'Alto', tipo: 'ORGANIZACIONAL', titulo: 'Plano de adequacao do ambiente de trabalho', descricao: 'Elaborar plano de melhorias nas condicoes fisicas (iluminacao, ergonomia, temperatura, ruido) com cronograma e orcamento.', responsavel: 'SESMT + Facilities', prazoSugerido: 'Curto prazo (60 dias)', referenciaLegal: 'NR-17; NR-24; ISO 45003', prioridade: 2 },
    { categoria: 'Seguranca e Condicoes', fatorNR1: 'Condicoes do ambiente', nivelRisco: 'Moderado', tipo: 'COLETIVA', titulo: 'SIPAT com foco em seguranca psicologica', descricao: 'Incluir temas de seguranca psicologica, estresse e saude mental na SIPAT anual.', responsavel: 'SESMT + CIPA', prazoSugerido: 'Medio prazo (conforme calendario)', referenciaLegal: 'NR-5; ISO 45003', prioridade: 3 },
    { categoria: 'Seguranca e Condicoes', fatorNR1: 'Condicoes do ambiente', nivelRisco: 'Baixo', tipo: 'ORGANIZACIONAL', titulo: 'Auditorias periodicas de condicoes ambientais', descricao: 'Manter calendario semestral de auditorias de condicoes do ambiente com checklists padronizados.', responsavel: 'SESMT', prazoSugerido: 'Continuo', referenciaLegal: 'NR-1 item 1.5.4', prioridade: 4 },

    // --- SAUDE EMOCIONAL ---
    { categoria: 'Saude Emocional', fatorNR1: 'Exigencias emocionais', nivelRisco: 'Critico', tipo: 'INDIVIDUAL', titulo: 'Atendimento psicologico emergencial', descricao: 'Disponibilizar atendimento psicologico individual imediato e gratuito. Encaminhar casos graves para acompanhamento clinico externo.', responsavel: 'SESMT + RH', prazoSugerido: 'Imediato (7 dias)', referenciaLegal: 'NR-7; NR-1; ISO 45003 seção 8.4', prioridade: 1 },
    { categoria: 'Saude Emocional', fatorNR1: 'Exigencias emocionais', nivelRisco: 'Critico', tipo: 'ORGANIZACIONAL', titulo: 'Investigacao de fatores de esgotamento', descricao: 'Conduzir entrevistas sigilosas nos setores criticos para identificar fatores especificos de esgotamento emocional. Atuar nas causas raiz.', responsavel: 'RH + SESMT', prazoSugerido: 'Imediato (30 dias)', referenciaLegal: 'NR-1 item 1.5.3; ISO 45003', prioridade: 1 },
    { categoria: 'Saude Emocional', fatorNR1: 'Exigencias emocionais', nivelRisco: 'Alto', tipo: 'COLETIVA', titulo: 'Programa de saude mental no trabalho', descricao: 'Implementar programa estruturado de saude mental: rodas de conversa, psicoeducacao, treinamento de primeiros socorros psicologicos para gestores.', responsavel: 'RH + SESMT', prazoSugerido: 'Curto prazo (60 dias)', referenciaLegal: 'ISO 45003 seção 8.3 e 8.4', prioridade: 2 },
    { categoria: 'Saude Emocional', fatorNR1: 'Exigencias emocionais', nivelRisco: 'Alto', tipo: 'ORGANIZACIONAL', titulo: 'Revisao de exigencias emocionais por funcao', descricao: 'Mapear funcoes com alta demanda emocional (atendimento, reclamacoes, luto) e oferecer suporte diferenciado: rodizio, pausas, supervisao.', responsavel: 'Gestores + RH', prazoSugerido: 'Curto prazo (60 dias)', referenciaLegal: 'ISO 45003 seção 6.2.9', prioridade: 2 },
    { categoria: 'Saude Emocional', fatorNR1: 'Exigencias emocionais', nivelRisco: 'Moderado', tipo: 'INDIVIDUAL', titulo: 'Canal de apoio psicologico permanente', descricao: 'Manter canal de apoio psicologico acessivel (presencial ou remoto) para todos os colaboradores.', responsavel: 'RH', prazoSugerido: 'Medio prazo (90 dias)', referenciaLegal: 'ISO 45003 seção 8.4', prioridade: 3 },
    { categoria: 'Saude Emocional', fatorNR1: 'Exigencias emocionais', nivelRisco: 'Baixo', tipo: 'COLETIVA', titulo: 'Campanhas de conscientizacao em saude mental', descricao: 'Manter campanhas periodicas (Janeiro Branco, Setembro Amarelo) com conteudo pratico e acesso a recursos de apoio.', responsavel: 'RH + Comunicacao', prazoSugerido: 'Continuo', referenciaLegal: 'ISO 45003 seção 8.3', prioridade: 4 },
  ]

  await prisma.medidaControle.createMany({ data: medidas })
  console.log(`${medidas.length} medidas de controle criadas.`)

  // ============================================================
  // CAUSAS PROVAVEIS
  // ============================================================
  const causas = [
    // Carga de Trabalho
    { categoria: 'Carga de Trabalho', fatorNR1: 'Exigencias da tarefa', titulo: 'Subdimensionamento do quadro de pessoal', descricao: 'Numero insuficiente de colaboradores para o volume de demandas do setor, gerando sobrecarga cronica.', impactos: 'Aumento de horas extras, absenteismo, erros operacionais, esgotamento fisico e mental.', indicadorRelacionado: 'Horas extras sistematicas, absenteismo elevado', evidencia: 'Medias baixas em itens de carga e ritmo de trabalho' },
    { categoria: 'Carga de Trabalho', fatorNR1: 'Exigencias da tarefa', titulo: 'Metas incompativeis com recursos disponiveis', descricao: 'Definicao de metas e prazos sem considerar a capacidade real da equipe.', impactos: 'Frustacao, queda de qualidade, presenteismo, rotatividade.', indicadorRelacionado: 'Turnover, reclamacoes sobre prazo', evidencia: 'Percepcao de pressao excessiva nos itens invertidos' },
    { categoria: 'Carga de Trabalho', fatorNR1: 'Exigencias da tarefa', titulo: 'Distribuicao desigual de tarefas', descricao: 'Concentracao de demandas em poucos colaboradores enquanto outros tem carga menor.', impactos: 'Sobrecarga localizada, conflitos internos, desmotivacao.', indicadorRelacionado: 'Variacao de horas extras entre colaboradores do mesmo setor', evidencia: 'Dispersao alta nas respostas do setor' },

    // Autonomia e Controle
    { categoria: 'Autonomia e Controle', fatorNR1: 'Grau de autonomia', titulo: 'Cultura de microgerenciamento', descricao: 'Gestores que centralizam decisoes e controlam excessivamente a execucao das tarefas.', impactos: 'Desmotivacao, perda de iniciativa, apatia, rotatividade.', indicadorRelacionado: 'Baixa percepcao de autonomia, reclamacoes sobre gestao', evidencia: 'Medias baixas em itens de autonomia e participacao' },
    { categoria: 'Autonomia e Controle', fatorNR1: 'Grau de autonomia', titulo: 'Ausencia de canais de participacao', descricao: 'Inexistencia de mecanismos formais para que colaboradores contribuam com ideias e decisoes.', impactos: 'Alienacao, baixo engajamento, sensacao de irrelevancia.', indicadorRelacionado: 'Engajamento baixo, pouca inovacao interna', evidencia: 'Medias baixas no item de participacao em decisoes' },

    // Relacoes Interpessoais
    { categoria: 'Relacoes Interpessoais', fatorNR1: 'Relacoes socioprofissionais', titulo: 'Tolerancia institucional ao assedio', descricao: 'Ausencia de politica anti-assedio efetiva ou impunidade em casos conhecidos.', impactos: 'Adoecimento mental, rotatividade, processos trabalhistas, dano reputacional.', indicadorRelacionado: 'Denuncias, afastamentos, acoes judiciais', evidencia: 'Medias criticas no item de assedio (invertido)' },
    { categoria: 'Relacoes Interpessoais', fatorNR1: 'Relacoes socioprofissionais', titulo: 'Conflitos nao mediados entre equipes', descricao: 'Disputas interpessoais ou entre setores sem intervencao gerencial ou mediacao.', impactos: 'Clima hostil, queda de cooperacao, silos organizacionais.', indicadorRelacionado: 'Reclamacoes de clima, pedidos de transferencia', evidencia: 'Medias abaixo do esperado em relacao entre pares e suporte social' },

    // Lideranca e Gestao
    { categoria: 'Lideranca e Gestao', fatorNR1: 'Estilo de gestao', titulo: 'Lideranca autoritaria ou negligente', descricao: 'Gestores com estilo de lideranca que gera medo, desrespeito ou abandono gerencial.', impactos: 'Estresse cronico, baixa confianca, rotatividade, absenteismo.', indicadorRelacionado: 'Turnover do setor, reclamacoes sobre chefia', evidencia: 'Medias baixas em respeito da chefia e feedback' },
    { categoria: 'Lideranca e Gestao', fatorNR1: 'Estilo de gestao', titulo: 'Ausencia de feedback e comunicacao', descricao: 'Colaboradores nao recebem retorno sobre desempenho, expectativas ou reconhecimento.', impactos: 'Inseguranca, desalinhamento, queda de performance.', indicadorRelacionado: 'Percepcao de reconhecimento, clareza de papel', evidencia: 'Medias baixas em feedback e comunicacao' },

    // Reconhecimento e Crescimento
    { categoria: 'Reconhecimento e Crescimento', fatorNR1: 'Reconhecimento', titulo: 'Ausencia de politica de reconhecimento', descricao: 'Empresa nao possui mecanismos formais ou informais de valorizacao do trabalho realizado.', impactos: 'Desmotivacao, desengajamento, busca por oportunidades externas.', indicadorRelacionado: 'Turnover voluntario, queda de produtividade', evidencia: 'Medias baixas em reconhecimento e valorizacao' },
    { categoria: 'Reconhecimento e Crescimento', fatorNR1: 'Reconhecimento', titulo: 'Falta de perspectiva de crescimento', descricao: 'Inexistencia de plano de carreira ou trilha de desenvolvimento acessivel.', impactos: 'Estagnacao profissional, fuga de talentos, apatia.', indicadorRelacionado: 'Tempo medio de permanencia, turnover', evidencia: 'Medias baixas em oportunidades de crescimento' },

    // Equilibrio Trabalho-Vida
    { categoria: 'Equilibrio Trabalho-Vida', fatorNR1: 'Jornada de trabalho', titulo: 'Cultura de disponibilidade permanente', descricao: 'Expectativa explicita ou implicita de que colaboradores estejam disponiveis fora do horario de trabalho.', impactos: 'Esgotamento, conflitos familiares, insonia, burnout.', indicadorRelacionado: 'Mensagens fora de horario, horas extras, atestados', evidencia: 'Medias criticas no item de demandas fora do horario (invertido)' },
    { categoria: 'Equilibrio Trabalho-Vida', fatorNR1: 'Jornada de trabalho', titulo: 'Jornada excessiva ou irregular', descricao: 'Jornadas superiores ao permitido ou escalas que comprometem o descanso.', impactos: 'Fadiga cronica, acidentes, adoecimento.', indicadorRelacionado: 'Horas extras, absenteismo, acidentes', evidencia: 'Medias baixas em equilibrio trabalho-vida' },

    // Clareza de Papel
    { categoria: 'Clareza de Papel', fatorNR1: 'Exigencias da tarefa', titulo: 'Descricoes de cargo desatualizadas ou inexistentes', descricao: 'Funcoes sem descricao formal de responsabilidades, gerando ambiguidade e conflito de papel.', impactos: 'Retrabalho, conflitos, ansiedade, queda de performance.', indicadorRelacionado: 'Reclamacoes sobre escopo, conflitos de responsabilidade', evidencia: 'Medias baixas em clareza de responsabilidades' },

    // Seguranca e Condicoes
    { categoria: 'Seguranca e Condicoes', fatorNR1: 'Condicoes do ambiente', titulo: 'Condicoes fisicas precarias ou inseguras', descricao: 'Ambiente de trabalho com deficiencias em iluminacao, ergonomia, temperatura, higiene ou seguranca.', impactos: 'Acidentes, doencas ocupacionais, insatisfacao, afastamentos.', indicadorRelacionado: 'CATs, atestados, reclamacoes sobre infraestrutura', evidencia: 'Medias baixas em seguranca e condicoes fisicas' },
    { categoria: 'Seguranca e Condicoes', fatorNR1: 'Condicoes do ambiente', titulo: 'Percepcao de inseguranca psicologica', descricao: 'Colaboradores nao se sentem seguros para expressar opinioes, relatar problemas ou pedir ajuda.', impactos: 'Silenciamento, ocultacao de erros, estresse, isolamento.', indicadorRelacionado: 'Participacao em pesquisas, uso de canais de denuncia', evidencia: 'Medias baixas em seguranca percebida' },

    // Saude Emocional
    { categoria: 'Saude Emocional', fatorNR1: 'Exigencias emocionais', titulo: 'Exposicao cronica a estressores sem suporte', descricao: 'Colaboradores lidam com demandas emocionais intensas (clientes dificeis, metas de pressao, conflitos) sem apoio institucional.', impactos: 'Burnout, ansiedade, depressao, afastamentos prolongados.', indicadorRelacionado: 'Afastamentos por CID F, uso de medicacao psicoativa', evidencia: 'Medias criticas em impacto emocional e esgotamento (invertidos)' },
    { categoria: 'Saude Emocional', fatorNR1: 'Exigencias emocionais', titulo: 'Ausencia de programa de saude mental', descricao: 'Empresa nao oferece recursos de apoio psicologico ou programas de prevencao ao adoecimento mental.', impactos: 'Agravamento de quadros, cronificacao, custos com afastamentos.', indicadorRelacionado: 'Oferta de atendimento psicologico, acoes preventivas', evidencia: 'Medias baixas em saude emocional combinada com ausencia de suporte reportado' },
  ]

  await prisma.causaProvavel.createMany({ data: causas })
  console.log(`${causas.length} causas provaveis criadas.`)

  console.log('Seed de medidas e causas finalizado com sucesso!')
}

main()
  .catch((e) => { console.error('Erro no seed:', e); process.exit(1) })
  .finally(async () => { await prisma.$disconnect() })
